import { ChakraProvider } from "@chakra-ui/react";
import { UserContextProvider } from "../context/userState";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <UserContextProvider>{children}</UserContextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
